runtime: python313

entrypoint: gunicorn -b :$PORT borroo.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "borroo.settings.production"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "borroo"
  DB_USER: "kako"
  DB_PASSWORD: "yIWkgNBhoASsEhNQPnfK499rW1oLwjNR"
  DB_HOST: "dpg-cv4p208fnakc73br5ga0-a.frankfurt-postgres.render.com"
  DB_PORT: "5432"

handlers:
  
- url: /static
  static_dir: static/
- url: /media
  static_dir: media/
- url: /.*
  script: auto