runtime: python312

service: backend-s2

entrypoint: gunicorn -b :$PORT borroo.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "borroo.settings"
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "borroos2_yourselfno"
  DB_USER: "borroos2_yourselfno"
  DB_PASSWORD: "0a6e3d627b99f3d4defd584ad9fc74d54f14cace"
  DB_HOST: "mtgf4.h.filess.io"
  DB_PORT: "61000"

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*
    script: auto

network:
  instance_tag: allow-mariadb