runtime: python312

service: backend-s3

entrypoint: gunicorn -b :$PORT borroo.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "borroo.settings"
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "borroos3_commonsoil"
  DB_USER: "borroos3_commonsoil"
  DB_PASSWORD: "b7ae2730d3316a2a98426ad61acf65d08a2321d2"
  DB_HOST: "6itmm.h.filess.io"
  DB_PORT: "61000"

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*
    script: auto

network:
  instance_tag: allow-mariadb