runtime: python312

service: backend-ppl

entrypoint: gunicorn -b :$PORT borroo.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "borroo.settings"
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "borroo-ppl-db"
  DB_USER: "borroo_user"
  DB_PASSWORD: "Borroo_25"
  CLOUD_SQL_CONNECTION_NAME: "issp-g4-db:europe-west1:issp-db-1"
  PRIVATE_IP: "true"  # Si estás usando una conexión privada

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*
    script: auto

beta_settings:
  cloud_sql_instances: "issp-g4-db:europe-west1:issp-db-1"