# Generated by Django 5.1.6 on 2025-03-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_category', models.CharField(
                    choices=[
                        ('ELECTRONICS', 'Electronics'),
                        ('TOOLS', 'Tools'),
                        ('SPORTS_EQUIPMENT', 'Sports Equipment'),
                        ('CAMPING_GEAR', 'Camping Gear'),
                        ('HOME_APPLIANCES', 'Home Appliances'),
                        ('FURNITURE', 'Furniture'),
                        ('PARTY_SUPPLIES', 'Party Supplies'),
                        ('COSTUMES', 'Costumes'),
                        ('PHOTOGRAPHY_EQUIPMENT', 'Photography Equipment'),
                        ('AUDIOVISUAL_EQUIPMENT', 'Audiovisual Equipment'),
                        ('GARDENING_TOOLS', 'Gardening Tools'),
                        ('OFFICE_EQUIPMENT', 'Office Equipment'),
                        ('CONSTRUCTION_EQUIPMENT', 'Construction Equipment'),
                        ('TRAVEL_ACCESSORIES', 'Travel Accessories'),
                        ('MEDICAL_EQUIPMENT', 'Medical Equipment'),
                        ('GAMES_AND_CONSOLES', 'Games and Consoles'),
                    ],
                    max_length=50
                )),
                ('cancel_type', models.CharField(
                    choices=[
                        ('FLEXIBLE', 'Flexible'),
                        ('MEDIUM', 'Medium'),
                        ('STRICT', 'Strict'),
                    ],
                    max_length=10
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
