# Generated by Django 5.1.6 on 2025-03-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_category', models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long')], max_length=10)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('price3', models.FloatField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='item.item')),
            ],
        ),
    ]
