# Generated by Django 5.1.6 on 2025-04-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objetos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "rent_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("requested", "Requested"),
                            ("booked", "Booked"),
                            ("picked_up", "Picked Up"),
                            ("returned", "Returned"),
                            ("rated", "Rated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("cancelled", "Cancelled"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_price", models.FloatField(default=0.0)),
                ("commission", models.FloatField(default=0.0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rents",
                        to="objetos.item",
                    ),
                ),
            ],
        ),
    ]
