# Generated by Django 5.1.6 on 2025-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rent_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('requested', 'Requested'), ('booked', 'Booked'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('rated', 'Rated'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
