# Generated by Django 5.1.6 on 2025-04-07 00:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verify_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="La contraseña debe contener al menos 8 caracteres,una mayúscula, un número y un carácter especial.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La contraseña debe contener al menos 8 caracteres,una mayúscula, un número y un carácter especial.",
                        regex="^(?=.*[A-Z])",
                    ),
                    django.core.validators.RegexValidator(
                        message="La contraseña debe contener al menos 8 caracteres,una mayúscula, un número y un carácter especial.",
                        regex="^(?=.*\\d)",
                    ),
                    django.core.validators.RegexValidator(
                        message="La contraseña debe contener al menos 8 caracteres,una mayúscula, un número y un carácter especial.",
                        regex='^(?=.*[!@#$%^&*()_+\\-=\\[\\]{};:"\\\\|,.<>\\/?])',
                    ),
                    django.core.validators.RegexValidator(
                        message="La contraseña debe contener al menos 8 caracteres,una mayúscula, un número y un carácter especial.",
                        regex="^.{8,}$",
                    ),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mensaje de Odio", "Mensaje de Odio"),
                            ("Información Engañosa", "Información Engañosa"),
                            (
                                "Se hace pasar por otra persona",
                                "Se hace pasar por otra persona",
                            ),
                            ("Otro", "Otro"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En revisión", "En revisión"),
                            ("Resuelto", "Resuelto"),
                        ],
                        default="Pendiente",
                        max_length=255,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
