# Generated by Django 5.1.6 on 2025-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0002_user_stripe_customer_id_user_stripe_subscription_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dni",
        ),
        migrations.AddField(
            model_name="user",
            name="_dni",
            field=models.CharField(
                blank=True, db_column="dni", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_subscription_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
