# Generated by Django 5.1.6 on 2025-04-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagos", "0001_initial"),
        ("rentas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="rent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="rentas.rent",
            ),
        ),
    ]
