# Generated by Django 5.1.6 on 2025-04-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_initial"),
        ("rentas", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidPendingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_confirmed_by_owner",
                    models.BooleanField(
                        help_text="Indica si el propietario ha confirmado el pago.",
                        null=True,
                    ),
                ),
                (
                    "is_confirmed_by_renter",
                    models.BooleanField(
                        help_text="Indica si el arrendatario ha confirmado el pago.",
                        null=True,
                    ),
                ),
                (
                    "rent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_pending_confirmation",
                        to="rentas.rent",
                    ),
                ),
            ],
        ),
    ]
