name: Validate Commit Messages

on:
  push:
    branches:
      - '**'

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Commit Messages
        run: |
          # Recorre los commits del push actual
          git log --oneline FETCH_HEAD | while read -r commit; do
            # Extrae el mensaje ignorando el hash
            message=$(echo "$commit" | sed 's/^[a-f0-9]* //')

            # Excluir commit de fusión
            if [[ "$message" =~ ^Merge ]]; then
              continue  # Saltar la validación si es un commit de fusión
            fi

            # Validar el mensaje según los tipos definidos (sin exigir mayúscula en el título)
            if [[ ! "$message" =~ ^(feat|fix|refactor|docs|test|conf):[[:space:]]+([a-zA-ZáéíóúÁÉÍÓÚüÜñÑ0-9]+.*) ]]; then
              echo "Invalid commit message: $message"
              echo "Expected format: 'type: subject' where type is one of [feat, fix, refactor, docs, test, conf] and subject starts with a verb in participle."
              exit 1
            fi
          done
