# Generated by Django 5.1.6 on 2025-03-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Tecnología'), ('sports', 'Deporte'), ('diy', 'Bricolaje'), ('clothing', 'Ropa'), ('furniture_and_logistics', 'Mobiliario y logística'), ('training', 'Entrenamiento')], max_length=50)),
                ('cancel_type', models.CharField(choices=[('flexible', 'Flexible'), ('medium', 'Medio'), ('strict', 'Estricto')], max_length=10)),
                ('price_category', models.CharField(choices=[('hour', 'Hora'), ('day', 'Día'), ('week', 'Semana'), ('month', 'Mes'), ('year', 'Año')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
