# Generated by Django 5.1.6 on 2025-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('drills_and_screwdrivers', 'Drills And Screwdrivers'), ('electricity_and_energy', 'Electricidad y energía'), ('sawing_and_cutting', 'Serrado y corte'), ('measuring_instruments', 'Instrumentos de medición'), ('ventilation', 'Ventilación'), ('hand_tools', 'Herramientas manuales'), ('paint_and_wallpaper', 'Pintura y papel tapiz'), ('other_construction_tools', 'Other Construction Tools'), ('compressed_air', 'Aire comprimido'), ('sound', 'Sonido'), ('drone', 'Dron'), ('projector_and_tv', 'Proyector y TV'), ('video_games', 'Videojuegos'), ('computers_and_accessories', 'Computers And Accessories'), ('other_electronics', 'Otros en electrónica'), ('mobile_phones_and_tablets', 'Mobile Phones And Tablets'), ('radio', 'Radio'), ('office_machinery', 'Maquinaria de oficina'), ('payment_terminal', 'Terminal de pago'), ('camera_battery', 'Batería de cámara'), ('camera_lenses', 'Lentes de cámara'), ('cameras', 'Cámaras'), ('color_sensor', 'Sensor de color'), ('flash_and_lights', 'Flash y luces'), ('memory_card', 'Tarjeta de memoria'), ('monitor', 'Monitor'), ('photo_background', 'Fondo para fotografía'), ('photo_printer', 'Impresora fotográfica'), ('teleprompter', 'Teleprompter'), ('underwater_camera_bodies', 'Underwater Camera Bodies'), ('other_cinema_photography', 'Other Cinema Photography'), ('garden_furniture', 'Muebles de jardín'), ('cable_laying_machine', 'Máquina tendecables'), ('chainsaw', 'Motosierra'), ('brush_cutter', 'Desbrozadora'), ('garden_roller', 'Rodillo para jardín'), ('leaf_blower', 'Soplador de hojas'), ('lawn_mower', 'Cortacésped'), ('other_garden_machinery', 'Other Garden Machinery')], max_length=50)),
                ('cancel_type', models.CharField(choices=[('flexible', 'Flexible'), ('medium', 'Medium'), ('strict', 'Strict')], max_length=10)),
                ('price_category', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
