# Generated by Django 5.1.6 on 2025-03-19 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('technology', 'Tecnología'), ('sports', 'Deporte'), ('diy', 'Bricolaje'), ('clothing', 'Ropa'), ('furniture_and_logistics', 'Mobiliario y logística'), ('training', 'Entrenamiento')], max_length=50)),
                ('cancel_type', models.CharField(choices=[('flexible', 'Flexible'), ('medium', 'Medio'), ('strict', 'Estricto')], max_length=10)),
                ('price_category', models.CharField(choices=[('hour', 'Hora'), ('day', 'Día'), ('week', 'Semana'), ('month', 'Mes'), ('year', 'Año')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a 0.'), django.core.validators.MaxValueValidator(99999999.99, message='El precio no puede ser                                   mayor a 99,999,999.99.'), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='objetos.item')),
            ],
        ),
    ]
