# Generated by Django 5.1.6 on 2025-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
