# Generated by Django 5.1.6 on 2025-03-20 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0001_initial'),
        ('usuarios', '0002_user_reset_token_user_reset_token_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='draft_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('technology', 'Tecnología'), ('sports', 'Deporte'), ('diy', 'Bricolaje'), ('clothing', 'Ropa'), ('furniture_and_logistics', 'Mobiliario y logística'), ('training', 'Entrenamiento')], max_length=50)),
                ('cancel_type', models.CharField(choices=[('flexible', 'Flexible'), ('medium', 'Medio'), ('strict', 'Estricto')], max_length=10)),
                ('price_category', models.CharField(choices=[('hour', 'Hora'), ('day', 'Día'), ('week', 'Semana'), ('month', 'Mes'), ('year', 'Año')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a 0.'), django.core.validators.MaxValueValidator(99999999.99, message='El precio no puede ser mayor a 99,999,999.99.'), django.core.validators.DecimalValidator(decimal_places=2, max_digits=10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='usuarios.user')),
            ],
        ),
    ]
