# Generated by Django 5.1.6 on 2025-04-10 11:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objetos", "0003_item_num_likes_alter_item_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="El precio debe ser mayor a 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        99999999.99,
                        message="El precio no puede ser                                   mayor a 99,999,999.99.",
                    ),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemrequest",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"), message="El precio debe ser mayor a 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("99999999.99"),
                        message="El precio no puede ser mayor a 99,999,999.99.",
                    ),
                    django.core.validators.DecimalValidator(
                        decimal_places=2, max_digits=10
                    ),
                ],
            ),
        ),
    ]
